import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Box from "@mui/material/Box";
import Header from "./components/HeaderComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box sx={{ flexGrow: 1 }}>
          <Header />
          {children}
        </Box>
      </body>
    </html>
  );
}
